workflows:
  ios-workflow:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - flutter build ios --release --no-codesign
      - flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
